In [6]:
#140
import sqlite3

def viewphonebook():
    cursor.execute("SELECT * FROM Names")
    for x in cursor.fetchall():
        print(x)
        
def addtophonebook():
    newid = int(input("Enter ID: "))
    newfname = input("Enter first name: ")
    newsname = input("Enter surname: ")
    newpnum = int(input("Enter phone number: "))
    cursor.execute("""INSERT INTO Names (id, firstname, surname, phonenumber)
    VALUES (?, ?, ?, ?)""", (newid, newfname, newsname, newpnum))
    db.commit()
    
def selectname():
    selectsurname = input("Enter a surname: ")
    cursor.execute("SELECT * FROM Names WHERE surname = ?", [selectsurname])
    for x in cursor.fetchall():
        print(x)
        
def deletedata():
    selectid = int(input("Enter ID: "))
    cursor.execute("DELETE FROM Names WHERE id = ?", [selectid])
    cursor.execute("SELECT * FROM Names")
    for x in cursor.fetchall():
        print(x)
    db.commit()
    
    
with sqlite3.connect("Phonebook.db") as db:
    cursor = db.cursor()
    
again = "y"
while again == "y":
    print()
    print("Main Menu")
    print()
    print("""1) View phone book \n2) Add to phone book \n3) Search for surname \n4) Delete person from phone book \n5) Quit \n""")
    selection = int(input("Enter your selection: "))
    
    if selection == 1:
        viewphonebook()
    elif selection == 2:
        addtophonebook()
    elif selection == 3:
        selectname()
    elif selection == 4:
        deletedata()
    elif selection == 5:
        again = "n"
    else:
        print("Incorrect selection entered")
        
db.close()

Main Menu

1) View phone book
2) Add to phone book
3) Search for surname
4) Delete person from phone book
5) Quit

Enter your selection: 1
(1, 'Simon', 'Howels', '01223 349752')
(2, 'Karen', 'Phillips', '01954 295773')
(3, 'Darren', 'Smith', '01583 749012')
(4, 'Anne', 'Jones', '01323 567322')
(5, 'Mark', 'Smith', '01223 855534')
(123, 'Kang', 'Yoon', '12345')

Main Menu

1) View phone book
2) Add to phone book
3) Search for surname
4) Delete person from phone book
5) Quit

Enter your selection: 4
Enter ID: 123
(1, 'Simon', 'Howels', '01223 349752')
(2, 'Karen', 'Phillips', '01954 295773')
(3, 'Darren', 'Smith', '01583 749012')
(4, 'Anne', 'Jones', '01323 567322')
(5, 'Mark', 'Smith', '01223 855534')

Main Menu

1) View phone book
2) Add to phone book
3) Search for surname
4) Delete person from phone book
5) Quit

Enter your selection: 3
Enter a surname: Smith
(3, 'Darren', 'Smith', '01583 749012')
(5, 'Mark', 'Smith', '01223 855534')

Main Menu

1) View phone book
2) Add to phone book
3) Search for surname
4) Delete person from phone book
5) Quit

Enter your selection: 5